#!/usr/bin/env bash
set -euo pipefail

BASE_BRANCH="${BASE_BRANCH:-master}"
BRANCH_NAME="${BRANCH_NAME:-automation/fork-governor-sync}"
DONORS_PATH="${DONORS_PATH:-DONORS.yaml}"
PR_TITLE="${PR_TITLE:-chore(donors): refresh fork inventory}"

if [ -z "${GH_TOKEN:-}" ]; then
  echo "Missing GH_TOKEN for PR helper." >&2
  exit 1
fi

find_open_pr() {
  gh pr list --state open --head "$BRANCH_NAME" --json number --jq '.[0].number // empty'
}

enable_auto_merge() {
  local pr_number="$1"

  if gh pr merge "$pr_number" --auto --squash --delete-branch; then
    echo "Auto-merge enabled for PR #${pr_number}."
  else
    echo "::warning::Unable to enable auto-merge for PR #${pr_number}. Check repository auto-merge settings and branch protection."
  fi
}

git config user.name "fork-governor[bot]"
git config user.email "fork-governor[bot]@users.noreply.github.com"
git checkout -B "$BRANCH_NAME"
git add "$DONORS_PATH"

BODY_FILE="$(mktemp)"
cat >"$BODY_FILE" <<'EOF'
## Summary
- refresh `DONORS.yaml` from live fork inventory when the inventory materially changes
- bootstrap the upstream sync workflow into newly discovered forks
- keep this generated PR auto-mergeable once checks are green

## Task contract
Plan: PR_BODY
- Verification: yes
- Rollback: yes

## Problem
The fork-governor PR must stay mergeable and should not create noisy timestamp-only PR churn.

## Smallest useful wedge
Keep generated donor refresh PRs focused on material `DONORS.yaml` changes, close stale generated PRs when no material change remains, and request auto-merge after the PR is created or updated.

## Verification plan
Rely on repository pull request checks, including `ci` and `task-readiness`, before auto-merge completes.

## Rollback plan
Revert the generated donor PR or this helper change to restore the previous manual merge behavior.

## Notes
This PR is generated by the fork governor workflow.
Timestamp-only donor refreshes are intentionally ignored so the workflow does not create unmergeable or noisy PR churn.
If a fork is locked or needs manual resolution, that status will appear in `DONORS.yaml`.
EOF

PR_NUMBER="$(find_open_pr)"

if git diff --cached --quiet; then
  echo "No staged DONORS changes."
  if [ -n "$PR_NUMBER" ]; then
    gh pr comment "$PR_NUMBER" --body "Closing stale fork-governor PR: the latest governor run found no material DONORS.yaml changes."
    gh pr close "$PR_NUMBER" --delete-branch || gh pr close "$PR_NUMBER"
  fi
  exit 0
fi

git commit -m "chore(donors): refresh fork inventory"
git push --force-with-lease origin "$BRANCH_NAME"

PR_NUMBER="$(find_open_pr)"
if [ -n "$PR_NUMBER" ]; then
  gh pr edit "$PR_NUMBER" --title "$PR_TITLE" --body-file "$BODY_FILE"
else
  gh pr create --base "$BASE_BRANCH" --head "$BRANCH_NAME" --title "$PR_TITLE" --body-file "$BODY_FILE"
  PR_NUMBER="$(find_open_pr)"
fi

if [ -z "$PR_NUMBER" ]; then
  echo "Unable to find or create fork-governor PR for ${BRANCH_NAME}." >&2
  exit 1
fi

enable_auto_merge "$PR_NUMBER"
